# Generated by Django 3.0.5 on 2020-04-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20200414_0931"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[("email", "Email"), ("github", "Github"), ("kakao", "Kakao")],
                default="email",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_secret",
            field=models.CharField(default="", max_length=20),
        ),
    ]
