# Generated by Django 3.0.4 on 2020-03-20 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_auto_20200320_1157"),
    ]

    operations = [
        migrations.RenameField(model_name="room", old_name="address", new_name="city",),
    ]
