# Generated by Django 3.0.4 on 2020-03-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_auto_20200324_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="address",
            field=models.CharField(blank="True", max_length=140),
        ),
    ]
