# Generated by Django 3.0.5 on 2020-04-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_room_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="guests",
            field=models.IntegerField(help_text="How many people will be staying?"),
        ),
    ]
